# Generated by Django 2.2.1 on 2019-09-13 16:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_examcandidatevalidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcandidatephoto',
            name='matching_percentages',
        ),
        migrations.AlterField(
            model_name='exam',
            name='capture_image_time',
            field=models.IntegerField(default=30, help_text='In Seconds'),
        ),
        migrations.AlterField(
            model_name='examcandidatephoto',
            name='detected_persons',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Detected persons list'),
        ),
    ]
