version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx/https_ssl:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
      - ./src/social_media_analysis:/src
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
    networks:
      - djangonetwork
  
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  web:
    build:
      context: ./src/social_media_analysis
      dockerfile: ../../compose/django/Dockerfile
    container_name: web
    volumes:
      - ./src/social_media_analysis:/src
    expose:
      - "443"
    env_file:
      - ./envs/django/dev.env
    links:
      - redis
    networks:
      - djangonetwork

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - djangonetwork
    restart: always


networks:
  djangonetwork:
    driver: bridge