# Generated by Django 2.2.1 on 2019-08-27 13:05

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegistrationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='In Minutes', max_length=150, null=True)),
                ('img', models.FileField(upload_to=candidate.models.user_dataset_directory_path)),
                ('is_valid', models.BooleanField(default=True)),
                ('more_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
