# Generated by Django 2.2.5 on 2019-12-09 06:00

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20190829_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateimgdataset',
            name='face',
            field=models.FileField(blank=True, help_text='face extracted from image by MTCNN face detector', null=True),
        ),
        migrations.AddField(
            model_name='candidateimgdataset',
            name='face_embedding',
            field=models.FileField(blank=True, help_text='Embedding(feature) extracted by Facenet model in 128d', null=True),
        ),
    ]
