# Generated by Django 2.2.5 on 2020-03-24 14:23

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20200324_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateimgdataset',
            name='face_embeddings',
        ),
        migrations.RemoveField(
            model_name='candidateimgdataset',
            name='total_face_embeddings',
        ),
        migrations.AddField(
            model_name='candidateimgdataset',
            name='face_embedding',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='Embedding(feature) extracted by Facenet model in 128d', null=True),
        ),
    ]
