# Generated by Django 2.2.1 on 2019-09-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20190913_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcandidatephoto',
            name='detected_persons',
        ),
    ]
