# Generated by Django 2.2.1 on 2019-09-13 16:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_examcandidatephoto_detected_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidatephoto',
            name='detected_persons_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Detected persons list'),
        ),
    ]
