# Generated by Django 2.2.1 on 2019-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanswer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
