# Generated by Django 2.2.1 on 2019-08-30 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_candidateanswer_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswer',
            name='selected_option',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='selected option sequences -- can be empty if not answered', null=True, size=None),
        ),
    ]
