# Generated by Django 2.2.1 on 2019-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190830_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='capture_image_time',
            field=models.IntegerField(default=10, help_text='In Seconds'),
        ),
        migrations.AddField(
            model_name='exam',
            name='suspicious_show_warning_after',
            field=models.IntegerField(default=2, help_text='Show warning to user after two consecutive suspicious activity'),
        ),
        migrations.AddField(
            model_name='exam',
            name='suspicious_stop_exam_after',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='examcandidatephoto',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Is activity is suspicious'),
        ),
    ]
