# Generated by Django 2.2.1 on 2019-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_examcandidatephoto_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidate',
            name='exam_remaining_time',
            field=models.IntegerField(blank=True, help_text='Exam remaining time in seconds', null=True),
        ),
    ]
