# Generated by Django 2.2.1 on 2019-09-14 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20190914_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcandidatephoto',
            name='user',
        ),
        migrations.AddField(
            model_name='examcandidatephoto',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.ExamCandidate'),
        ),
        migrations.AlterField(
            model_name='examcandidatephoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examcandidatevalidation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
