# Generated by Django 2.2.5 on 2019-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20190914_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidatephoto',
            name='is_emotion_calc_done',
            field=models.BooleanField(default=False, help_text='Is emotion calculation done'),
        ),
        migrations.AddField(
            model_name='examcandidatephoto',
            name='is_object_detection_done',
            field=models.BooleanField(default=False, help_text='Is object detection done'),
        ),
    ]
