# Generated by Django 2.2.5 on 2019-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20191201_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidatephoto',
            name='emotion_message',
            field=models.TextField(blank=True, help_text='Message after calculating emotion', null=True),
        ),
    ]
