# Generated by Django 2.2.5 on 2019-12-09 06:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_examcandidatephoto_emotion_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcandidatephoto',
            name='emotions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='person face with emotions -- happy, sad, fear'),
        ),
    ]
