# Generated by Django 2.2.5 on 2019-12-15 19:04

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20191209_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidatephoto',
            name='np_face',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='face extracted from image by MTCNN face detector of authorized user', null=True),
        ),
        migrations.AddField(
            model_name='examcandidatephoto',
            name='np_highlighted_faces',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='highlighted_faces extracted from image', null=True),
        ),
    ]
