# Generated by Django 2.2.1 on 2019-08-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_tempregistrationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempregistrationimage',
            name='session_id',
        ),
        migrations.AddField(
            model_name='tempregistrationimage',
            name='lazy_user_id',
            field=models.IntegerField(blank=True, help_text='Temp user id', null=True),
        ),
        migrations.AlterField(
            model_name='tempregistrationimage',
            name='img',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
