# Generated by Django 2.2.1 on 2019-08-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20190827_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregistrationimage',
            name='img',
            field=models.FileField(help_text='After successfull user registration move file to dataset folder', upload_to='temp/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tempregistrationimage',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
