# Generated by Django 2.2.5 on 2019-12-14 14:15

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20191209_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateimgdataset',
            name='face',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='face extracted from image by MTCNN face detector', null=True),
        ),
        migrations.AlterField(
            model_name='candidateimgdataset',
            name='face_embedding',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='Embedding(feature) extracted by Facenet model in 128d', null=True),
        ),
    ]
