# Generated by Django 2.2.5 on 2020-03-24 14:18

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20191214_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateimgdataset',
            name='face_embedding',
        ),
        migrations.AddField(
            model_name='candidateimgdataset',
            name='face_embeddings',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, help_text='Embedding(feature) extracted by Facenet model in 128d as list for all faces', null=True),
        ),
        migrations.AddField(
            model_name='candidateimgdataset',
            name='total_face_embeddings',
            field=models.IntegerField(blank=True, help_text='Total count of face embeddings', null=True),
        ),
    ]
