# Generated by Django 2.2.1 on 2019-09-14 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0010_auto_20190914_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcandidatephoto',
            name='candidate',
        ),
        migrations.AddField(
            model_name='examcandidatephoto',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam'),
        ),
        migrations.AddField(
            model_name='examcandidatephoto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
