# Generated by Django 2.2.5 on 2020-06-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20191229_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidate',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='restart_time',
            field=models.DateTimeField(blank=True, help_text='Last restart time.', null=True),
        ),
    ]
