# Generated by Django 2.2.5 on 2020-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20200628_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanswer',
            name='overwrite_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
