# Generated by Django 2.2.5 on 2020-07-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_candidateanswer_overwrite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcandidate',
            name='exam_stop_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='is_exam_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examcandidate',
            name='is_restart_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
